Script started on Tue Apr  1 13:55:04 2014
[?1034hbash-3.2$ ./testg++ Set.cpp setTestDriver.cpp Complex.cpp -o test[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[KexPtrs.cpp =[K-o testExec
[1mexPtrs.cpp:218:6: [0m[0;1;35mwarning: [0m[1m'/*' within block comment [-Wcomment][0m
     /********************** End Part 2 ***************************/
[0;1;32m     ^
[0m[1mexPtrs.cpp:263:5: [0m[0;1;35mwarning: [0m[1m'/*' within block comment [-Wcomment][0m
    /********************** End Part 3 ***************************/
[0;1;32m    ^
[0m2 warnings generated.
bash-3.2$ ./testExec

Part 1 - Pointer variables
Pointer ptrA has the data: 0x0
Pointer ptrB has the data: 0x0

Variable a is stored at address  0x7fff558b6768
Pointer ptrA is stored at address 0x7fff558b6758
Variable b is stored at address  0x7fff558b6764
Pointer ptrB is stored at address 0x7fff558b6750
Draw diagrams to illustrate the above 







 Using a, Variable a holds the value 225
Pointer ptrA holds the value 0x7fff558b6768

 Using ptrA, Variable a holds the value 225



After 1st assignment operation:  

The data stored in ptrA  is  0x7fff558b6768
Using ptrA, the data stored in a  is 225
Using a, the data stored in a  is 225

 ptrA is at location 0x7fff558b6758

 Using ptrA, a is at location 0x7fff558b6768

 Using a, a is at location 0x7fff558b6768
The data stored in ptrB  is 225
Using ptrB, the data stored in b  is 225
Using b, the data stored in b  is 167

 Using ptrB, b is at location 0x7fff558b6768

 Using b, b is at location 0x7fff558b6764
Draw diagrams to illustrate the above and explain what happened







After 2nd assignment operation 

The data stored in ptrA  is  0x7fff558b6768
Using ptrA, the data stored in a  is 987
Using a, the data stored in a  is 987

 ptrA is at location 0x7fff558b6758

 Using ptrA, a is at location 0x7fff558b6768

 Using a, a is at location 0x7fff558b6768
The data stored in ptrB  is 0x7fff558b6768
Using ptrB, the data stored in b  is 987
Using b, the data stored in b  is 167

 Using ptrB, b is at location 0x7fff558b6768

 Using b, b is at location 0x7fff558b6764
Draw diagrams to illustrate the above and explain what happened





bash-3.2$ exit
exit

Script done on Tue Apr  1 13:57:09 2014
